# Generated by Django 3.0.7 on 2020-06-20 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0002_auto_20200619_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
